spring:
  application:
    name: zuul-api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
      discovery:
        instance-id: gateway
        serviceName: express-${spring.application.name}


server:
  port: 9090


zuul:
  host:
    socket-timeout-millis: 300000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    insync:
      ribbon:
        ReadTimeout: 20000
      path: /api/product
      url: http://localhost:8080/api/product